name: A workflow for my Hello Stupido
on: push

jobs:
  build:
    name: Hello world action
    runs-on: alpine-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Grandiosos Stupidos"

